accounts/urls.py
from django.urls import path
from . import views
app_name="accounts"

urlpatterns=[
path('signup/', views.views_signup, name='signup'),
    path('login/', views.views_login, name='login'),
    path('logout/', views.views_logout, name='logout'),
    path('createProfile/', views.create_profile, name='create_profile'),
    path('<username>', views.user_profile, name='userProfile2'),
]

pro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


from . import views

app_name="home"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name="homepage"),
    path('accounts/', include('accounts.urls')),
    path('projects/', include('projects.urls')),
    path('search/', views.search, name="search"),
    path('search/submit', views.search, name="search"),
    path('test/', views.test, name="test"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from . import views
from accounts.views import user_profile


urlpatterns=[
    path('createProject/', views.create_project, name='create_project'),
    path('bookmarkIt/', views.bookmarkIt, name='bookmarkIt'),
    path('addComment/', views.addComment, name='addComment'),
    path('/accounts/<username>/' ,user_profile, name='userProfile1'),
    path('<slug>/', views.projectDetail, name='projectDetail'),

]

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import Profile

# Create your models here.

#comment bookmark like


class project_data(models.Model):
    title = models.CharField(max_length=100, primary_key=True)
    abstract = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique = True)
    files = models.FileField(blank = True)
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE)
    owner1 = models.CharField(default = 'None', max_length=120)
    category = models.CharField(max_length=150)

utility/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from projects.models import project_data
# Create your models here.


class bookmarks(models.Model):
    bookmark_slug = models.ForeignKey(project_data, on_delete=models.CASCADE)
    slug = models.SlugField()
    bookmark_title = models.CharField(max_length=100, primary_key=True)
    username = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    owner = models.CharField(max_length=100)

    def __str__(self):
        return self.bookmark_title

class comments(models.Model):
    comment_field = models.TextField()
    comment_on_slug = models.SlugField()
    comment_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    owner = models.CharField(max_length=100)
    comment_date = models.DateTimeField(auto_now_add=True)

projects/forms.py
from django import forms
from . import models
class create_project(forms.ModelForm):
    class Meta:
        #file_field = forms.FileField(widget=forms.ClearableFielInput(attrs={'mulitple':True}))
        model = models.project_data
        fields = ['title','abstract','slug','category','files']

projects/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt,csrf_protect
from django.contrib.auth.decorators import login_required
from . import forms
from accounts.models import Profile
from .models import project_data
from utility.models import bookmarks, comments
from utility.forms import post_comment



# Create your views here.
@csrf_exempt
@login_required()
def create_project(request):
    print(type(request.user))

    if request.method == 'POST':
        form = forms.create_project(request.POST,request.FILES)

        if form.is_valid():
            print("Valid project data")
            instance = form.save(commit=False)
            print('request.user')

            instance.owner = Profile.objects.get(username=str(request.user))
            instance.owner1 = str(request.user)
            instance.save()
            #return redirect('homepage')
            return projectDetail(request,instance.slug)
        else:
            print("Invalid form data")
            return HttpResponse("Invalid Form data, go back <br> <li> Try changing slug field </li>")
    else:

        form = forms.create_project()
        return render(request, 'projects/project_upload.html',{'form':form})

@csrf_exempt
def projectDetail(request,slug):
    project = get_object_or_404(project_data,slug = slug)
    #return HttpResponse(project.title)
    cmnt = post_comment()
    print(cmnt)

    allComments = comments.objects.values().filter(comment_on_slug = slug)

    return render(request,'projects/project_detail.html',{'project':project,'cmnt_form':cmnt, 'comments':allComments})

@csrf_exempt
def bookmarkIt(request):
    if request.method == 'POST':
        p_data = project_data.objects.get(slug = request.POST['slug'])

        if str(request.user) == str(p_data.owner1):
            print("both are same")
            return HttpResponse("You cannot bookmark your own project")
        else:

            instance = bookmarks(
                    bookmark_slug  = p_data,
                    bookmark_title = request.POST['title'],
                    username = request.user,
                    slug = request.POST['slug'],
                    owner = str(request.user)
                    )
            instance.save()
            print(instance)
            return HttpResponse("Surprise")
    else:
        return HttpResponse("Some error tooke place @bookmarkIt")

@csrf_exempt
def addComment(request):
    if request.method=='POST':
        instance = comments(
                comment_field = request.POST['comment_field'],
                comment_on_slug = request.POST['slug'],
                comment_by = request.user,
                owner = str(request.user)
                        )
        instance.save()
        print(instance)
        print("instance hopefully saved")

        return projectDetail(request,request.POST['slug'])

projects/templates/projects/project_detail.html
{% load static from staticfiles %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Procrate: {{user}}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/pricing/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <form class="form-inline my- my-lg-0" method="POST" action="/search/">
          <input class="form-control mr-3 sm-4" type="search" name="search" placeholder="Search" aria-label="Search" method="POST">

          <div class="btn-group btn-group-toggle" data-toggle="buttons">
              <label class="btn btn-secondary active">
                <input type="radio" name="options" id="s_user" value="user" autocomplete="off" checked> Users
              </label>
              <label class="btn btn-secondary">
                <input type="radio" name="options" id="s_project" value="project" autocomplete="off"> Projects
      </label>
        <label class="btn btn-secondary">
          <input type="radio" name="options" id="s_blog" value="blog" autocomplete="off"> Articles
        </labelsubmit>
          </div>

          <button class="btn btn-primary my-2 my-sm-0" type="submit" action = "search/" method="POST">Search</button>

    </form>
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'pricing.css'%}" rel="stylesheet">
  </head>
  <body>
      <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal"><a href="/">Procrate</h5>
    <nav class="my-2 my-md-0 mr-md-3">
      <a class="p-2 text-dark" href="#"></a>
      <a class="p-2 text-dark" href="#"></a>
      <a class="p-2 text-dark" href="#"></a>
    </nav>
    {% if user.is_authenticated %}
      <h5 class="my-0 mr-md-3 font-weight-normal"><a href="{% url 'userProfile1' user.username %}">{{user}}</h5>
      <a class="btn btn-outline-primary" href="{% url 'accounts:logout'%}" action="" method='POST'>Logout</a>
    {% else %}
      <a class="btn btn-outline-primary" href="{% url 'accounts:login'%}">Login</a>
      <a class="btn btn-outline-primary" href="{% url 'accounts:signup'%}">Sign up</a>
    {% endif %}
  </div>

  <div class="container">
    <div class="card-deck mb-3 text-center">
      <div class="card mb-4 shadow-sm">
        <div class="card-header">
          <h4 class="card-title pricing-card-title">{{ project.title }}</h4>


          <!-- bookmark thing ---->
          {% if user.is_authenticated %}
          {% if user.username != project.owner1 %}
          <form class="form-inline my- my-lg-0" method='POST' action="/projects/bookmarkIt/">
          <input type="hidden" name="slug" value="{{ project.slug }}">
          <input type="hidden" name="title" value="{{ project.title }}">
          <input class="btn btn-warning" type="submit" value="Bookmark It">
        </form>
        {%endif%}
        {%endif%}
        </div>
        <div class="card-body">
          <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">

      <p class="lead">{{ project.abstract}}.</p>
      <ul class="list-unstyled mt-3 mb-4">
              <li>{{ project.date }}</li>
              <li>Owner: {{ project.owner }}</li>
              <li>Category: {{ project.category}}</li>
            </ul>
    </div>
    <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Project Files</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title"></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li><a href="{{ project.files.url }}">{{ project.files}}</a></li>
            </ul>
            <!--button type="button" class="btn btn-lg btn-block btn-primary">Download</button-->
          </div>
        </div>

      <div class="container">
      <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Comments</h4>
          </div>
        </div>
      </div>
      <div class="card-deck mb-3 text-left">
        <div class="card-body">
            <h1 class="card-title pricing-card-title"> </h1>
            <ul class="list-unstyled mt-3 mb-4">
              {% for comment in comments.all%}
              <li>{{comment.comment_field}}</li>
              <label> {{comment.owner}} </label>
              <br>
              {{comment.comment_date}}
              <br>
              {%endfor%}
            </ul>



<!-- adding comment form .... django form modified !!!!!! -->
  {% if user.is_authenticated %}
      <form class="form-group" action="/projects/addComment/" method='POST' >


            <textarea name="comment_field" class='form-control' cols="30" rows="3" required id="id_comment_field">
              </textarea>
            <input type='hidden' value="{{project.slug}}" id="slug" name="slug"  >
            <input type='submit' value='Comment' method="POST">
          </form>

          <button type="button" class="btn btn-lg btn-block btn-outline-primary">Sign up for free</button>

          </div>
        </div>
        {% endif %}

projects/templates/projects/project_upload.html
{% load static from staticfiles %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Procrate: {{user}}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/pricing/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <form class="form-inline my- my-lg-0" method="POST" action="/search/">
          <input class="form-control mr-3 sm-4" type="search" name="search" placeholder="Search" aria-label="Search" method="POST">

          <div class="btn-group btn-group-toggle" data-toggle="buttons">
              <label class="btn btn-secondary active">
                <input type="radio" name="options" id="s_user" value="user" autocomplete="off" checked> Users
              </label>
              <label class="btn btn-secondary">
                <input type="radio" name="options" id="s_project" value="project" autocomplete="off"> Projects
      </label>
        <label class="btn btn-secondary">
          <input type="radio" name="options" id="s_blog" value="blog" autocomplete="off"> Articles
        </labelsubmit>
          </div>

          <button class="btn btn-primary my-2 my-sm-0" type="submit" action = "search/" method="POST">Search</button>

    </form>

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'pricing.css'%}" rel="stylesheet">
  </head>
  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal"><a href="/"> Procrate</a></h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <a class="p-2 text-dark" href="#"></a>
    <a class="p-2 text-dark" href="#"></a>
    <a class="p-2 text-dark" href="#"></a>

  </nav>
  {% if user.is_authenticated %}
    <h5 class="my-0 mr-md-3 font-weight-normal">{{user}}</h5>
    <a class="btn btn-outline-primary" href="{% url 'accounts:logout'%}" action="" method='POST'>Logout</a>
  {% else %}
    <a class="btn btn-outline-primary" href="{% url 'accounts:login'%}">Login</a>
    <a class="btn btn-outline-primary" href="{% url 'accounts:signup'%}">Sign up</a>
  {% endif %}
</div>



<div class = 'project-upload'>
  <form class="create-project" action="/projects/createProject/" method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type='submit' value='Upload' method="POST">